### ISSUE TITLE
Cleaning after failed install

### ISSUE THREAD

**Issue by ElucGeek** [CertainLach/VivePro2-Linux-Driver#13]
Hello,
I tried to install with nix but it failed with several errors. I think I'm not ready to make it works by myself so I will give up for now. How can I check what was already installed and how to clean up everything? Is there directories to look for?

**Comment by CertainLach** [comment]
Nix is not used for the installation, it is used for building release distribution, same as published on patreon

There is nothing installed during nix build, and here is commands to uninstall nix itself:
https://nixos.org/manual/nix/stable/installation/installing-binary.html#linux

**Comment by ElucGeek** [comment]
OK thanks for the help.
