### ISSUE TITLE
Failed to patch the Kernel using build-debian.sh

### ISSUE THREAD

**Issue by koehneiph** [CertainLach/VivePro2-Linux-Driver#21]
Hello,

first of all, thanks for your hard work to get the Vive Pro 2 working on Linux. I already did a donation on patron and installed the driver successfully. Right now I'm stuck at getting the kernel patch working. My system specs are as follows: 

System: Ubuntu 22.04 
Kernel: 5.19.0-46-generic
Graphic: NVIDIA RTX 3080
Driver Version: 525.125.06

running the ./build-debian.sh inside the /kernel-patches gives me the following error: 

![Screenshot from 2023-07-14 12-40-42](https://github.com/CertainLach/VivePro2-Linux-Driver/assets/139550586/657d2999-81b8-4935-92e3-2160233553c3)

any help is very appreciated!

**Comment by MarioCavero** [comment]
Hello! Quite some time since this comment but did you manage to fix it? I am facing the same issue. Before installing anything, patched kernel into ubuntu 22 should be done first? @koehneiph
