### ISSUE TITLE
DSC support tracking issue

### ISSUE THREAD

**Issue by CertainLach** [CertainLach/VivePro2-Linux-Driver#4]
Figured out whole DSC thing:
There is one useful `DisplayId` field reported by HMD: bits per pixel = 8.0

By default it is detected as 10.4375 in amdgpu driver
While running steamvr with noise on screen do
```sh
# Divide result (167) by 16 = 10.4375
cat /sys/kernel/debug/dri/0/DP-X/dsc_bits_per_pixel
```

But as EDID contains 8.0, we need to pass it manually
While steamvr is not running (Command above will return 0), do
```sh
# 8.0 * 16 = 128 = 0x80
echo 0x80 > /sys/kernel/debug/dri/0/DP-X/dsc_bits_per_pixel
```

And then steamvr will just work on max resolution

I am not sure how to implement this kernel patch myself,
it should be reported to amdgpu devs instead

P.S: `/sys/kernel/debug` = debugfs, you can mount it with
```
mount -t debugfs -f none /sys/kernel/debug
```

**Comment by CertainLach** [comment]
Cc: @nsf @CandyGumdrop

**Comment by nsf** [comment]
Wow, great news! I'll try it sometime tomorrow.

**Comment by nsf** [comment]
It worked, however I had to apply the number **after** starting steamvr. Tried the described flow - it didn't do anything.

**Comment by CertainLach** [comment]
It was easier than i thought, implemented patches for correct DSC support for amdgpu:
https://github.com/CertainLach/VivePro2-Linux-Driver/tree/master/kernel-patches/dsc

Not yet sent to mailing lists, i need to test some things before
